In [ ]:
import pandas as pd

In [ ]:
project=pd.read_excel('/content/final project.xlsx')

In [ ]:
project.columns

Index(['Type', 'real day of shipping', 'scheduled days of shipment',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Custom Name', 'Customer Id', 'Customer Segment',
       'Latitude', 'Longitude', 'Order City', 'Order Country',
       'Order Customer Id', 'order date (DateOrders)', 'Order Id',
       'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order Status',
       'Product Card Id', 'Product Category Id', 'Product Name',
       'Product Price', ' adj shipping date (order)', 'Shipping Mode'],
      dtype='object')

In [ ]:
project[' adj shipping date (order)']=pd.to_datetime(project[' adj shipping date (order)'],errors='coerce')

In [ ]:
print(project[' adj shipping date (order)'])

0     2018-02-03
1            NaT
2            NaT
3            NaT
4            NaT
         ...
995   2018-01-12
996          NaT
997          NaT
998   2017-12-06
999   2017-12-10
Name:  adj shipping date (order), Length: 1000, dtype: datetime64[ns]

In [ ]:
project['adj shipping date (order)'].dtype

dtype('<M8[ns]')

In [ ]:
project[' adj shipping date (order)'].fillna(pd.Timestamp.today().strftime('%Y-%m-%d'),inplace=True)

<ipython-input-10-e4ea28048980>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  project[' adj shipping date (order)'].fillna(pd.Timestamp.today().strftime('%Y-%m-%d'),inplace=True)

In [ ]:
project[' adj shipping date (order)']

0     2018-02-03
1     2025-03-07
2     2025-03-07
3     2025-03-07
4     2025-03-07
         ...
995   2018-01-12
996   2025-03-07
997   2025-03-07
998   2017-12-06
999   2017-12-10
Name:  adj shipping date (order), Length: 1000, dtype: datetime64[ns]

In [ ]:
project.to_excel('final_project.xlsx', index=False)

# edit on new file after excel edit 10/3

In [ ]:
project=pd.read_excel('/content/final_project.xlsx')

In [ ]:
project.columns

Index(['Type', 'real day of shipping', 'scheduled days of shipment',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Custom Name', 'Customer Id', 'Customer Segment',
       'Latitude', 'Longitude', 'Order City', 'Order Country',
       'Order Customer Id', 'order date (DateOrders)', 'Order Id',
       'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order Status',
       'Product Card Id', 'Product Category Id', 'Product Name',
       'Product Price', ' adj shipping date (order)', 'Shipping Mode'],
      dtype='object')

In [ ]:
# Calculate Shipping Delay
project["Shipping Delay"] = project["real day of shipping"] - project["scheduled days of shipment"]

# Add a column to describe the shipping status
project["Shipping Status"] = project["Shipping Delay"].apply(
    lambda x: "Shipped Earlier" if x < 0 else ("On Time" if x == 0 else "Shipped Late")
)

# Add a column to show the absolute number of days early or late
project["Shipping Delay Description"] = project["Shipping Delay"].apply(
    lambda x: f"{abs(x)} day(s) early" if x < 0 else ("On Time" if x == 0 else f"{x} day(s) late")
)

# Display the updated DataFrame
print(project[["real day of shipping", "scheduled days of shipment", "Shipping Delay", "Shipping Status", "Shipping Delay Description"]].head())

   real day of shipping  scheduled days of shipment  Shipping Delay  \
0                     3                           4              -1
1                     5                           4               1
2                     4                           4               0
3                     3                           4              -1
4                     2                           4              -2

   Shipping Status Shipping Delay Description
0  Shipped Earlier             1 day(s) early
1     Shipped Late              1 day(s) late
2          On Time                    On Time
3  Shipped Earlier             1 day(s) early
4  Shipped Earlier             2 day(s) early

In [ ]:
project[["real day of shipping", "scheduled days of shipment", "Shipping Delay", "Shipping Status", "Shipping Delay Description"]]

,real day of shipping,scheduled days of shipment,Shipping Delay,Shipping Status,Shipping Delay Description
0,3,4,-1,Shipped Earlier,1 day(s) early
1,5,4,1,Shipped Late,1 day(s) late
2,4,4,0,On Time,On Time
3,3,4,-1,Shipped Earlier,1 day(s) early
4,2,4,-2,Shipped Earlier,2 day(s) early
...,...,...,...,...,...
995,2,4,-2,Shipped Earlier,2 day(s) early
996,6,2,4,Shipped Late,4 day(s) late
997,5,2,3,Shipped Late,3 day(s) late
998,2,4,-2,Shipped Earlier,2 day(s) early
999,6,4,2,Shipped Late,2 day(s) late

In [ ]:
project['Order Status']=project['Order Status'].str.replace('_',' ')

In [ ]:
project['Order Status']

0             complete
1              pending
2               closed
3             complete
4      pending payment
            ...
995    pending payment
996    pending payment
997           canceled
998    pending payment
999         processing
Name: Order Status, Length: 1000, dtype: object

In [ ]:
project.drop(columns=['Shipping Delay','Shipping Status'],inplace=True)

In [ ]:
project.columns

Index(['Type', 'real day of shipping', 'scheduled days of shipment',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Custom Name', 'Customer Id', 'Customer Segment',
       'Latitude', 'Longitude', 'Order City', 'Order Country',
       'Order Customer Id', 'order date (DateOrders)', 'Order Id',
       'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order Status',
       'Product Card Id', 'Product Category Id', 'Product Name',
       'Product Price', ' adj shipping date (order)', 'Shipping Mode',
       'Shipping Delay Description'],
      dtype='object')

In [ ]:
project.to_excel('final_project1.xlsx', index=False)

In [ ]:
project = project.sort_values(by=['Customer Id','order date (DateOrders)' ])
project['Cumulative_Profit_by_Customer'] = project.groupby('Customer Id')['Order Profit Per Order'].cumsum()

In [ ]:
project['Cumulative_Profit_by_Customer']

761     24.530001
850     67.050003
600     74.360001
296    174.360001
443   -215.479996
          ...
217    102.510002
241     62.820000
728     50.500000
247     76.269997
0       91.250000
Name: Cumulative_Profit_by_Customer, Length: 1000, dtype: float64

In [ ]:


customer_order_counts = project['Customer Id'].value_counts().reset_index()
customer_order_counts.columns = ['Customer Id', 'Total Orders']

# Merge the new column with the original DataFrame
project = project.merge(customer_order_counts, on='Customer Id', how='left')
def classify_loyalty(orders):
    """Assigns a loyalty level based on the number of orders."""
    if orders >= 3:
        return 'High Loyalty'  # Frequent buyers
    elif orders >= 2:
        return 'Moderate Loyalty'  # Occasional buyers
    else:
        return 'Low Loyalty'  # One-time buyers

# Apply function to create loyalty column
project['Customer Loyalty'] = project['Total Orders'].apply(classify_loyalty)

In [ ]:
project['Customer Loyalty']

0      Low Loyalty
1      Low Loyalty
2      Low Loyalty
3      Low Loyalty
4      Low Loyalty
          ...
995    Low Loyalty
996    Low Loyalty
997    Low Loyalty
998    Low Loyalty
999    Low Loyalty
Name: Customer Loyalty, Length: 1000, dtype: object

In [ ]:
project

,Type,real day of shipping,scheduled days of shipment,Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Card Id,Product Category Id,Product Name,Product Price,adj shipping date (order),Shipping Mode,Shipping Delay Description,Cumulative_Profit_by_Customer,Total Orders,Customer Loyalty
0,debit,3,4,24.530001,52.189999,advance shipping,0,17,Cleats,Lawrence,...,365,17,Perfect Fitness Perfect Rip Deck,59.990002,2025-03-07,Standard Class,1 day(s) early,24.530001,1,Low Loyalty
1,debit,5,4,67.050003,254.960007,late delivery,1,17,Cleats,West New York,...,365,17,Perfect Fitness Perfect Rip Deck,59.990002,2025-03-07,Standard Class,1 day(s) late,67.050003,1,Low Loyalty
2,transfer,3,4,74.360001,220.000000,shipping canceled,0,24,Women's Apparel,Caguas,...,502,24,Nike Men's Dri-FIT Victory Golf Polo,50.000000,2017-02-12,Standard Class,1 day(s) early,74.360001,1,Low Loyalty
3,debit,5,4,174.360001,464.950012,late delivery,1,16,As Seen on TV!,Long Beach,...,359,16,Nike Men's Free TR 5.0 TB Training Shoe,99.989998,2017-09-07,Standard Class,1 day(s) late,174.360001,1,Low Loyalty
4,payment,2,2,-215.479996,293.970001,shipping on time,0,9,Cardio Equipment,Caguas,...,191,9,Nike Men's Free 5.0+ Running Shoe,99.989998,2025-03-07,Second Class,On Time,-215.479996,1,Low Loyalty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,debit,6,4,102.510002,205.029999,late delivery,1,76,Women's Clothing,Amarillo,...,1363,76,Summer dresses,215.820007,2018-02-02,Standard Class,2 day(s) late,102.510002,1,Low Loyalty
996,debit,2,4,62.820000,200.710007,advance shipping,0,76,Women's Clothing,Garden Grove,...,1363,76,Summer dresses,215.820007,2025-03-07,Standard Class,2 day(s) early,62.820000,1,Low Loyalty
997,debit,3,4,50.500000,194.240005,advance shipping,0,76,Women's Clothing,Fairfield,...,1363,76,Summer dresses,215.820007,2025-03-07,Standard Class,1 day(s) early,50.500000,1,Low Loyalty
998,debit,3,4,76.269997,200.710007,advance shipping,0,76,Women's Clothing,Mentor,...,1363,76,Summer dresses,215.820007,2018-02-02,Standard Class,1 day(s) early,76.269997,1,Low Loyalty
999,debit,3,4,91.250000,314.640015,advance shipping,0,73,Sporting Goods,Caguas,...,1360,73,Smart watch,327.750000,2018-02-03,Standard Class,1 day(s) early,91.250000,1,Low Loyalty

In [ ]:
project['Customer Loyalty']

In [ ]:
moderate_loyalty_customers = project[project['Customer Loyalty'] == 'Moderate Loyalty']
print(moderate_loyalty_customers.head)

<bound method NDFrame.head of Empty DataFrame
Columns: [Type, real day of shipping, scheduled days of shipment, Benefit per order, Sales per customer, Delivery Status, Late_delivery_risk, Category Id, Category Name, Customer City, Customer Country, Custom Name, Customer Id, Customer Segment, Latitude, Longitude, Order City, Order Country, Order Customer Id, order date (DateOrders), Order Id, Order Item Cardprod Id, Order Item Discount, Order Item Id, Order Item Product Price, Order Item Profit Ratio, Order Item Quantity, Sales, Order Item Total, Order Profit Per Order, Order Region, Order Status, Product Card Id, Product Category Id, Product Name, Product Price,  adj shipping date (order), Shipping Mode, Shipping Delay Description, Cumulative_Profit_by_Customer, Total Orders, Customer Loyalty]
Index: []

[0 rows x 42 columns]>

In [ ]:
project.drop(columns=['Customer Loyalty'],inplace=True)

In [ ]:
project['Customer Loyalty']

0      Low Loyalty
1      Low Loyalty
2      Low Loyalty
3      Low Loyalty
4      Low Loyalty
          ...
995    Low Loyalty
996    Low Loyalty
997    Low Loyalty
998    Low Loyalty
999    Low Loyalty
Name: Customer Loyalty, Length: 1000, dtype: object

In [ ]:
project.drop(columns=['Cumulative_Profit_by_Customer'],inplace=True)

In [ ]:
project

,Type,real day of shipping,scheduled days of shipment,Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Category Id,Product Name,Product Price,adj shipping date (order),Shipping Mode,Shipping Delay Description,Total Orders_x,Total Orders_y,Total Orders,Customer Loyalty
0,debit,3,4,24.530001,52.189999,advance shipping,0,17,Cleats,Lawrence,...,17,Perfect Fitness Perfect Rip Deck,59.990002,2025-03-07,Standard Class,1 day(s) early,1,1,1,Low Loyalty
1,debit,5,4,67.050003,254.960007,late delivery,1,17,Cleats,West New York,...,17,Perfect Fitness Perfect Rip Deck,59.990002,2025-03-07,Standard Class,1 day(s) late,1,1,1,Low Loyalty
2,transfer,3,4,74.360001,220.000000,shipping canceled,0,24,Women's Apparel,Caguas,...,24,Nike Men's Dri-FIT Victory Golf Polo,50.000000,2017-02-12,Standard Class,1 day(s) early,1,1,1,Low Loyalty
3,debit,5,4,174.360001,464.950012,late delivery,1,16,As Seen on TV!,Long Beach,...,16,Nike Men's Free TR 5.0 TB Training Shoe,99.989998,2017-09-07,Standard Class,1 day(s) late,1,1,1,Low Loyalty
4,payment,2,2,-215.479996,293.970001,shipping on time,0,9,Cardio Equipment,Caguas,...,9,Nike Men's Free 5.0+ Running Shoe,99.989998,2025-03-07,Second Class,On Time,1,1,1,Low Loyalty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,debit,6,4,102.510002,205.029999,late delivery,1,76,Women's Clothing,Amarillo,...,76,Summer dresses,215.820007,2018-02-02,Standard Class,2 day(s) late,1,1,1,Low Loyalty
996,debit,2,4,62.820000,200.710007,advance shipping,0,76,Women's Clothing,Garden Grove,...,76,Summer dresses,215.820007,2025-03-07,Standard Class,2 day(s) early,1,1,1,Low Loyalty
997,debit,3,4,50.500000,194.240005,advance shipping,0,76,Women's Clothing,Fairfield,...,76,Summer dresses,215.820007,2025-03-07,Standard Class,1 day(s) early,1,1,1,Low Loyalty
998,debit,3,4,76.269997,200.710007,advance shipping,0,76,Women's Clothing,Mentor,...,76,Summer dresses,215.820007,2018-02-02,Standard Class,1 day(s) early,1,1,1,Low Loyalty
999,debit,3,4,91.250000,314.640015,advance shipping,0,73,Sporting Goods,Caguas,...,73,Smart watch,327.750000,2018-02-03,Standard Class,1 day(s) early,1,1,1,Low Loyalty

In [ ]:
project.to_excel('final_project2.xlsx', index=False)